# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink:           pretty

# Dependencies
gems: [jekyll-paginate]

# Setup
title:               Tucker
tagline:             'Trying out Jekyll'
description:         'A Jekyll site by <a href="https://twitter.com/tckr" target="_blank">@tckr</a> built on Lanyon.'
url:                 http://tckr.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tucker Severson
  url:               https://twitter.com/tckr
  email:             tuckerseverson@gmail.com

# Custom vars
version:             1.0.0
